- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"
    - emit-ara-html

- hosts: "{{ site_logs.fqdn }}"
  gather_facts: False
  roles:
    - role: upload-logs
      zuul_log_url: "http://80.158.20.68"

#- hosts: localhost
#  ignore_errors: yes
#  roles:
#    - submit-logstash-jobs
#    - submit-subunit-jobs
